### ISSUE TITLE
Boot animation is not smooth and screen glitches after booting up

### ISSUE THREAD

**Issue by Divyansh-2903** [ChonDoit/treble_afterlife_patches#11]
My friend found some heating issues while gaming , overall UI is great , best rom in customisation nearly best overall , but heating issue is there

**Comment by ChonDoit** [comment]
Thermals are vendor side, GSI doesn't touch thems

**Comment by Divyansh-2903** [comment]
> Thermals are vendor side, GSI doesn't touch thems

Yeah but look if there are processes running in background maybe they can hear up device or is there any optimization problem??
