### ISSUE TITLE
heating issue 

### ISSUE THREAD

**Issue by Divyansh-2903** [ChonDoit/treble_afterlife_patches#12]
i know its a first build so bugs are expected but afterlife offers so much , i will be glad if youre able to fix heating issue and optimize this os further , as i was playing a team deathmatch for 8 mins , i felt a slight heat and my friend also reaported it , ill be adding other issues if i find in it, looking forward to your builds ❤️

**Comment by ChonDoit** [comment]
Thermals are vendor side, GSI doesn't touch thems

**Comment by Divyansh-2903** [comment]
> Thermals are vendor side, GSI doesn't touch thems

When can I expect the next update??

**Comment by Divyansh-2903** [comment]
when can i expect next update?

**Comment by Divyansh-2903** [comment]
can you make a gsi for my device , i can help you out with testing if you
want
i know gsis are not device specific but you can optimize it right?
